name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            run-benchmark: true
          - os: ubuntu-24.04-arm
            run-benchmark: true
          - os: macos-latest
            run-benchmark: false
          - os: windows-latest
            run-benchmark: true
          - os: windows-11-arm
            run-benchmark: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo +nightly fmt --check
      - run: cargo test
      - run: cargo test --features tokio
      - run: cargo clippy -- -D warnings
      - run: cargo clippy --features tokio -- -D warnings
      - run: cargo run --example detect
      - run: cargo run --example benchmark
        if: matrix.run-benchmark
